apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema" # required

# imports are filled via the Installation CRD specifying an import section.
imports:
- name: runtimeCluster
  targetType: landscaper.gardener.cloud/kubernetes-cluster
- name: gardenCluster
  targetType: landscaper.gardener.cloud/kubernetes-cluster
- name: imageVectorOverwrite
  required: false
  schema:
    type: string
- name: componentImageVectorOverwrites
  required: false
  schema:
    type: string
- name: seedBackup
  required: false
  schema:
    type: object
    properties:
      provider:
        type: string
#       provider specific credentials just parsed as string and created as secret
      credentials:
        type: object
- name: resources
  required: false
  schema:
    type: object
    properties:
      requests:
        type: object
        properties:
          cpu:
            type: string
          memory:
            type: string
      limits:
        type: object
        properties:
          cpu:
            type: string
          memory:
            type: string

# check example/20-componentconfig-gardenlet.yaml for what can be configured
- name: componentConfiguration
  schema:
    type: object

deployExecutions:
- name: default
  type: GoTemplate
  template: |
    deployItems:
    - name: deploy
      type: landscaper.gardener.cloud/container
      config:
        apiVersion: container.deployer.landscaper.gardener.cloud/v1alpha1
        kind: ProviderConfiguration

        blueprint:
          ref:
            repositoryContext:
    {{ toYaml ( index .cd.component.repositoryContexts (add (len .cd.component.repositoryContexts) -1) ) | indent 10 }}
            componentName: {{ .cd.component.name }}
            version: {{ .cd.component.version }}
            resourceName: blueprint

        importValues:
          apiVersion: gardenlet.gardener.landscaper.gardener.cloud/v1alpha1
          kind: Imports
    {{ toYaml .imports | indent 6 }}

        image: {{ index .cd.component.resources "gardenlet-landscaper" "access" "imageReference" }}
